[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
kernal = { version = "0.4.0", optional = true }

[dev-dependencies]
rstest = "0.24.0"
rstest_reuse = "0.7.0"
model = { path = ".", features = [ "test-util" ]}

[features]
test-util = [ "dep:kernal" ]
