[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
model = { path = "../model" }

[dev-dependencies]
model = { path = "../model", features = [ "test-util" ] }
kernal = "0.4.0"
rstest = "0.25.0"
