name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libxdo-dev
    - name: Version
      run: |
        rustup component add clippy
        rustup +nightly component add rustfmt
        rustup --version
        cargo --version
        cargo clippy --version
        cargo +nightly fmt --version
    - name: Build
      run: cargo build --verbose --all-features
    - name: Tests
      run: cargo test --verbose --all-features
    - name: Clippy
      run: cargo clippy --verbose --all-features
    - name: Rustfmt
      run: cargo +nightly fmt --all -- --check
    - name: Documentation
      run: cargo doc --verbose --all-features --no-deps

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libxdo-dev
      - name: Install Dioxus-CLI
        run: cargo install --verbose dioxus-cli@0.7.0-alpha.2
      - name: Build
        run: dx bundle --verbose --release --package frontend --platform web
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server-dir: ./
          local-dir: ./target/dx/frontend/release/web/public/
          protocol: ftps
