name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy --verbose --all-features
    - name: Build
      run: cargo build --verbose --all-features
    - name: Tests
      run: cargo test --verbose --all-features
    - name: Documentation
      run: cargo doc --verbose --all-features
