name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev libxdo-dev
    - name: Version
      run: |
        rustup component add clippy
        rustup +nightly component add rustfmt
        rustup --version
        cargo --version
        cargo clippy --version
        cargo +nightly fmt --version
    - name: Build
      run: cargo build --verbose --all-features
    - name: Tests
      run: cargo test --verbose --all-features
    - name: Clippy
      run: cargo clippy --verbose --all-features
    - name: Rustfmt
      run: cargo +nightly fmt --all -- --check
    - name: Documentation
      run: cargo doc --verbose --all-features
